# Generated by Django 3.2.5 on 2021-12-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Краткое SEO описание', null=True, verbose_name='meta keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.TextField(blank=True, help_text='SEO заголовок', null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Краткое SEO описание', null=True, verbose_name='meta keywords'),
        ),
        migrations.AddField(
            model_name='tag',
            name='seo_title',
            field=models.TextField(blank=True, help_text='SEO заголовок', null=True, verbose_name='meta description'),
        ),
    ]
