# Generated by Django 3.2.5 on 2021-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок', max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(help_text='Краткое описание', verbose_name='Краткое описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('is_pub', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
