# Generated by Django 3.2.5 on 2021-08-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(default='/', help_text='Ссылка', max_length=200, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
