# Generated by Django 3.2.5 on 2021-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/images/', verbose_name='Картинка 370x220'),
        ),
    ]
