# Generated by Django 3.2.5 on 2021-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_additionallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, help_text='Фамилия', max_length=200, null=True, verbose_name='Фамилия')),
                ('description', models.TextField(help_text='Тест сообщения', verbose_name='Тест сообщения')),
                ('email', models.EmailField(help_text='Email', max_length=254, verbose_name='Email')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('cv_url', models.CharField(blank=True, help_text='Ссылка', max_length=200, null=True, verbose_name='Ссылка')),
                ('type', models.CharField(blank=True, choices=[('KO', 'Консультация'), ('PS', 'Пробное собеседование')], max_length=2, null=True)),
            ],
            options={
                'ordering': ('add_date',),
            },
        ),
    ]
